[package]
name = "rbr-plugin"
version = "0.1.0"
authors = ["Robert <r@robertmasen.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rbr-plugin-runner = { path = "../../" }

[lib]
crate-type = ["cdylib"]